### ISSUE TITLE
Add support for annotation

### ISSUE THREAD

**Issue by sxsmg** [shivaprsd/doqment#1]
Annotation and highlighting in native firefox pdf viewer is absent. Hoping for this feature to be included.

**Comment by shivaprsd** [comment]
I know this is a much demanded feature of PDF.js. I am indeed planning to add more features in addition to the Reader mode and Annotation is definitely on my list.

Many projects have already been written for this, so it's just a matter of integration. Meanwhile it looks like PDF.js maintainers are themselves [working on this](https://github.com/mozilla/pdf.js/issues/14975). :rocket:

So I consider it best to wait and watch.

**Comment by shivaprsd** [comment]
Annotation feature now enabled on the `dev` branch (3d80e0e34d6e853287fc3b9c99afa0bdc2c1347c).

Seems like this has been available for the last two release versions of PDF.js. It is still off by default in the default viewer, so we have enabled it.

**Comment by shivaprsd** [comment]
Annotation feature now enabled on the dev branch (3d80e0e).

Seems like this has been available for the last two release versions of PDF.js. It is still off by default in the default viewer, so we have enabled it.

**Comment by shivaprsd** [comment]
This is set to launch in next release. Currently the PDF.js team has added annotation support only; we can hope they will add a text highlighter as well soon.

**Comment by shivaprsd** [comment]
@sxsmg Feel free to reopen this if you are not satisfied with this resolution.
