### ISSUE TITLE
Custom overlays?

### ISSUE THREAD

**Issue by aehlke** [shivaprsd/doqment#11]
Sorry for the naive question, new to pdf.js and this excellent lib - is there a way to add an overlay layer, such that I could define bounding boxes for "button" areas of each page in HTML; or such that I could custom provide a text layer for text selection and tappable text elements? Thanks

**Comment by shivaprsd** [comment]
Hi @aehlke, thanks for stopping by!

I'm afraid there isn't any built-in API for the specific things you ask. You could poke around in `overlay_manager.js` and `text_layer_builder.js` in the PDF.js source code I guess. Or just write a custom overlay.

To run your code in *doqment*, you would have to include your script and pack from source. A good endpoint for this would be `src/scripts/extension.js`; that is where I hook into the viewer's code. Just import your file at the end.

If you have any more doubt, please feel free to ask.

**Comment by shivaprsd** [comment]
@aehlke Let me close this issue as answered. If you have more questions feel free to reopen.

**Comment by aehlke** [comment]
@shivaprsd thabks so much for the helpful leads!

**Comment by shivaprsd** [comment]
@aehlke One more tip: if you are running in the browser, there is a global `PDFViewerApplication` object exported by PDF.js to access various components of the viewer.
