### ISSUE TITLE
Need to set PDF.js preferences 

### ISSUE THREAD

**Issue by MagicalDrizzle** [shivaprsd/doqment#2]
It seems that since pdf.js only honors `prefers-color-scheme`, setting `privacy.resistFingerprinting = true` will force it to be white, and people have been asking for a manual dark mode toggle for quite a while: https://github.com/mozilla/pdf.js/issues/12290

The official pdf.js team however seems to have made a [pref](https://github.com/mozilla/pdf.js/issues/12290#issuecomment-763739702) specifically for this, but that doesn't apply to doqment for obvious reasons

Could a manual toggle be implemented?

**Comment by shivaprsd** [comment]
Thanks for pointing this out! I did know of that pref, but I did not know about `privacy.resistFingerprinting` and its effect on `prefers-color-scheme`.

I would be hard-pressed to implement a manual toggle; even the original maintainers could not find a way to modify the needed CSS dynamically – see https://github.com/mozilla/pdf.js/pull/12625#issue-743267748. 🙃

A wider-scoped workaround would be to provide an [Options page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Options_pages) to set the pref, as well as the other prefs. This has been wanting since v0.1 and I've been planning to add one on the lines of the PDF.js Chrome extension.

**Comment by MagicalDrizzle** [comment]
it'd definitely be good enough!
> provide an Options page to set the pref, as well as the other prefs.
oh that was what I meant by "manual toggle" oops

**Comment by shivaprsd** [comment]
Great!

> oh that was what I meant by "manual toggle" oops

Somebody was asking for a manual toggle button on the toolbar itself, so I thought you meant that. 😅

This should be ready by [v0.3](https://github.com/users/shivaprsd/projects/1)

**Comment by shivaprsd** [comment]
I am deferring this to a future release. The Options page would need some work, and I have other finished features to ship.

**Comment by shivaprsd** [comment]
@MagicalDrizzle Sorry about that! I'm sort of too busy to work on it at the moment. 😥

Meanwhile can you try the method given in https://github.com/shivaprsd/doqment/issues/5#issuecomment-1421103657? You'll have to execute something like:
```js
PDFViewerApplication.preferences.set('viewerCssTheme', 2)    /* for dark */
```

It's not as convenient as an options page, still, better than nothing for the time being.

**Comment by MagicalDrizzle** [comment]
@shivaprsd It just returns a not defined error for me...
![not defined](https://github.com/shivaprsd/doqment/assets/49761211/0a320f4f-ec99-4be4-bb37-d9fb6eb00011)

**Comment by shivaprsd** [comment]
@MagicalDrizzle Can you tell me what OS & browser you use and their versions? And also the version of _doqment_?

The code should be executed in the console opened for a _doqment_ tab, with or without any PDF loaded. But I guess you are doing just that, looking at the screenshot. I am curious why it shouldn't work.

**Comment by MagicalDrizzle** [comment]
Windows 10 19045.2965, Firefox 114.0.1, doqment v0.4

**Comment by MagicalDrizzle** [comment]
@shivaprsd It seems it only works when you open the extension page itself (so address bar shows the "ugly" moz-extension url)
If you paste it in a tab with something other than that (like when you paste the DOI in scihub) then it won't work (probably for obvious reasons)
![ugly](https://github.com/shivaprsd/doqment/assets/49761211/15d7ac38-0897-44fe-b1f6-bdc5a437c945)

**Comment by shivaprsd** [comment]
> On that particular page (and many others), the pdf is shown inside an <iframe>

@KiitoX I had suspected this. But I didn't know the button shows up only in pages with iframes. Thanks for clearing it up! 

> It seems it only works when you open the extension page itself

@MagicalDrizzle Yes, correct. Just execute it with the value `2` in the extension page and reload it. It will then start to apply everywhere automatically, including iframes, so you _don't_ have to do it again for the other page.

You can use the same command to revert it as well. The values are 0 = automatic (default), 1 = always light, 2 = always dark.

**Comment by shivaprsd** [comment]
The Options page is in the works, and should be ready by the next release. The progress can be tracked [here](/shivaprsd/doqment/tree/options).

Currently it looks like this, embedded in Extension Settings in Firefox (feedback welcome):
![options-page](https://github.com/shivaprsd/doqment/assets/18247990/20b4c018-3abe-4b0e-92e6-60906d4c0763)

The values are viewer defaults, but any overrides set via the console are respected; so migration won’t be a problem.

**Comment by MagicalDrizzle** [comment]
do your best! 
I will say this extension has basically saved my eyesights as I look at sci-hub all the time at 2am...
I'm glad to be able to see it develop ^^

**Comment by shivaprsd** [comment]
@MagicalDrizzle Version 0.7 in now live in the Add-ons store.

Happy New Year! 🎉
