### ISSUE TITLE
[Feature Request] Make the URL of the document copyable

### ISSUE THREAD

**Issue by kuro68k** [shivaprsd/doqment#21]
Currently when you view a PDF in Doqment, the URL bar shows the extension ID and an encoded URL (non-Latin characters use HTML encoding).

It would be extremely handy to be to able to copy the URL of the document, without encoding. A button or menu item would suffice.

**Comment by shivaprsd** [comment]
@kuro68k This feature is already available!

- Chrome: right click on the extension icon
- Firefox: click on the 🔗 icon that appears in the address bar

**Comment by kuro68k** [comment]
Thanks. I didn't think to click on the icon as it is hidden by default.
